name: Process Search Term Report

on:
  schedule:
    # 每天UTC时间00:00自动运行
    - cron: '0 0 * * *'
  push:
    branches:
      - main  # 或您想要触发此操作的分支

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy openpyxl
    - name: Run script
      run: main.py
